version: "3.8"

services:
  web:
    build: .
    image: coderj001/django_chatapp
    container_name: django_chatapp
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./web-env
    links:
      - cache
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    env_file:
      - ./pgdb-env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
  cache:
    image: redis:alpine
    container_name: cache
    restart: always

volumes:
  pgdata:
